### ISSUE TITLE
cookie无法解析

### ISSUE THREAD

**Issue by mdjso** [Hobr/comicup29-ticket-buy#1]
在浏览器获取到的cookie和python字典的值无法对应，请问是有什么转换规则吗？
没有直接看到“name”，“path” 的值。

**Comment by Keke-nA** [comment]
作者大大用这个抢到了没呀

**Comment by Hobr** [comment]
> 作者大大用这个抢到了没呀

抢到了，在b站捡漏了别人退的day1，在cp官网刷到了随机放票的day2。但这只是个工具，不建议完全依靠它来抢，用的时候还得自己看情况修改代码

**Comment by Keke-nA** [comment]
改了一下下 能够运行了hhhh[https://github.com/Keke-nA/picture/blob/main/2)RXV9B(%5D%60HJG%40%242(B%7DGYIK.png](url)

**Comment by Keke-nA** [comment]
改了一下下 能够运行了hhhh[https://github.com/Keke-nA/picture/blob/main/2)RXV9B(%5D%60HJG%40%242(B%7DGYIK.png](url)

**Comment by Keke-nA** [comment]
改了一下下能运行了hhhh[https://github.com/Keke-nA/picture/blob/main/2)RXV9B(%5D%60HJG%40%242(B%7DGYIK.png](url)

**Comment by Keke-nA** [comment]
改了一下能运行了hhhhh[](https://github.com/Keke-nA/picture/blob/main/2)RXV9B(%5D%60HJG%40%242(B%7DGYIK.png)

**Comment by Keke-nA** [comment]
改了一下下能运行了hhhh

**Comment by Keke-nA** [comment]
我第一次买这票  是脚本抢票成功后会自动提交订单然后自己随时去付款，还是要立马在界面上付款呀？

**Comment by Hobr** [comment]
> 我第一次买这票 是脚本抢票成功后会自动提交订单然后自己随时去付款，还是要立马在界面上付款呀？

脚本成功到付款界面后就可以关掉了，10分钟内到平台的订单页面支付即可

**Comment by Keke-nA** [comment]
> > 我第一次买这票 是脚本抢票成功后会自动提交订单然后自己随时去付款，还是要立马在界面上付款呀？
> 
> 脚本成功到付款界面后就可以关掉了，10分钟内到平台的订单页面支付即可

好的好的谢谢谢谢！

**Comment by Sherlockliu7777** [comment]
> 我是先魔改了一下脚本，手动登录一次后输出cookie ~这个脚本还有很多问题，需要一边用一边自己改~
> 
> ```python
> cookies = WebDriver.get_cookies()
> print(cookies)
> ```

作者大大，加了你这两行代码以后，是不是后面的
WebDriver.add_cookie(
    {
        'domain':cookie['domain'],
        'name': cookie['name'],
        'value':cookie['value'],
        'path': cookie['path']
    }
这里不用自己手动输入domain,name,value,path的值了，它会自动变成对应的值么？

**Comment by Hobr** [comment]
> > 我是先魔改了一下脚本，手动登录一次后输出cookie ~这个脚本还有很多问题，需要一边用一边自己改~
> > ```python
> > cookies = WebDriver.get_cookies()
> > print(cookies)
> > ```
> 
> 作者大大，加了你这两行代码以后，是不是后面的 WebDriver.add_cookie( { 'domain':cookie['domain'], 'name': cookie['name'], 'value':cookie['value'], 'path': cookie['path'] } 这里不用自己手动输入domain,name,value,path的值了，它会自动变成对应的值么？

不是的，这个是用来获取cookie的，你可以新建一个py文件然后复制下面这段进去并运行，在弹出的浏览器里自己手动登录一次，20s后终端会输出cookie，关掉现在的终端，把输出的内容对应填到脚本里就行，也可以通过其他方法获取cookie并按格式填入。

```python
from selenium.webdriver.common.by import By
from selenium import webdriver
import time

WebDriver = webdriver.Chrome()
WebDriver.get("https://show.bilibili.com/platform/detail.html?id=72320")
time.sleep(20)
cookies = WebDriver.get_cookies()
print(cookies)
```

**Comment by Sherlockliu7777** [comment]
作者大大，那是抢票之前，提前先在代码里填好cookie里的这些字段是吧？ cookie应该是一段时间内不会变的吧？

> > > 我是先魔改了一下脚本，手动登录一次后输出cookie ~这个脚本还有很多问题，需要一边用一边自己改~
> > > ```python
> > > cookies = WebDriver.get_cookies()
> > > print(cookies)
> > > ```
> > 
> > 
> > 作者大大，加了你这两行代码以后，是不是后面的 WebDriver.add_cookie( { 'domain':cookie['domain'], 'name': cookie['name'], 'value':cookie['value'], 'path': cookie['path'] } 这里不用自己手动输入domain,name,value,path的值了，它会自动变成对应的值么？
> 
> 不是的，这个是用来获取cookie的，你可以新建一个py文件然后复制下面这段进去并运行，在弹出的浏览器里自己手动登录一次，20s后终端会输出cookie，关掉现在的终端，把输出的内容对应填到脚本里就行，也可以通过其他方法获取cookie并按格式填入。
> 
> ```python
> from selenium.webdriver.common.by import By
> from selenium import webdriver
> import time
> 
> WebDriver = webdriver.Chrome()
> WebDriver.get("https://show.bilibili.com/platform/detail.html?id=72320")
> time.sleep(20)
> cookies = WebDriver.get_cookies()
> print(cookies)
> ```

作者大大，那是抢票之前，提前先在代码里填好cookie里的这些字段是吧？ cookie应该是一段时间内不会变的吧？

**Comment by Hobr** [comment]
> 作者大大，那是抢票之前，提前先在代码里填好cookie里的这些字段是吧？ cookie应该是一段时间内不会变的吧？
> 
> > > > 我是先魔改了一下脚本，手动登录一次后输出cookie ~这个脚本还有很多问题，需要一边用一边自己改~
> > > > ```python
> > > > cookies = WebDriver.get_cookies()
> > > > print(cookies)
> > > > ```
> > > 
> > > 
> > > 作者大大，加了你这两行代码以后，是不是后面的 WebDriver.add_cookie( { 'domain':cookie['domain'], 'name': cookie['name'], 'value':cookie['value'], 'path': cookie['path'] } 这里不用自己手动输入domain,name,value,path的值了，它会自动变成对应的值么？
> > 
> > 
> > 不是的，这个是用来获取cookie的，你可以新建一个py文件然后复制下面这段进去并运行，在弹出的浏览器里自己手动登录一次，20s后终端会输出cookie，关掉现在的终端，把输出的内容对应填到脚本里就行，也可以通过其他方法获取cookie并按格式填入。
> > ```python
> > from selenium.webdriver.common.by import By
> > from selenium import webdriver
> > import time
> > 
> > WebDriver = webdriver.Chrome()
> > WebDriver.get("https://show.bilibili.com/platform/detail.html?id=72320")
> > time.sleep(20)
> > cookies = WebDriver.get_cookies()
> > print(cookies)
> > ```
> 
> 作者大大，那是抢票之前，提前先在代码里填好cookie里的这些字段是吧？ cookie应该是一段时间内不会变的吧？

是的，cookie短时间内不会变，至少我的从昨晚到现在都没改过

**Comment by Cihnomi** [comment]
作者大大，请问下状态里显示无法购票是什么情况啊

**Comment by Hobr** [comment]
> 作者大大，请问下状态里显示无法购票是什么情况啊

因为现在没票了，你要是想捡漏的话可以一直挂着，等着他一直刷新到购买按钮亮了

**Comment by gx2816** [comment]
作者大大，请问为啥B站可以自动刷新，但是cpp运行后会打开页面报错后自动关闭
Traceback (most recent call last):
  File "E:/py脚本/comicup29-ticket-buy-main/cpp.py", line 34, in <module>
    WebDriver.add_cookie(
  File "E:\py脚本\comicup29-ticket-buy-main\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 727, in add_cookie
    self.execute(Command.ADD_COOKIE, {"cookie": cookie_dict})File "E:\py脚本\comicup29-ticket-buy-main\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "E:\py脚本\comicup29-ticket-buy-main\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidCookieDomainException: Message: invalid cookie domain: Cookie 'domain' mismatch
  (Session info: chrome=111.0.5563.147)
Stacktrace:
Backtrace:
	(No symbol) [0x0086DCE3]
	(No symbol) [0x008039D1]
	((No symbol) [0x00714DA8]
	(No symbol) [0x0077A8DF]
	(No symbol) [0x0075AECC]
	(No symbol) [0x0076D57C]
	(No symbol) [0x0075ACC6]
	(No symbol) [0x00736F68]
	(No symbol) [0x007380CD]
	GetHandleVerifier [0x00AE3832+2506274]
	GetHandleVerifier [0x00B19794+2727300]
	GetHandleVerifier [0x00B1E36C+2746716]
	GetHandleVerifier [0x00916690+617600]
	(No symbol) [0x0080C712]
	(No symbol) [0x00811FF8]
	(No symbol) [0x008120DB]
	(No symbol) [0x0081C63B]
	BaseThreadInitThunk [0x7646FA29+25]
	RtlGetAppContainerNamedObjectPath [0x779E7A7E+286]
	RtlGetAppContainerNamedObjectPath [0x779E7A4E+238]

**Comment by Hobr** [comment]
> 作者大大，请问为啥B站可以自动刷新，但是cpp运行后会打开页面报错后自动关闭 Traceback (most recent call last): File "E:/py脚本/comicup29-ticket-buy-main/cpp.py", line 34, in WebDriver.add_cookie( File "E:\py脚本\comicup29-ticket-buy-main\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 727, in add_cookie self.execute(Command.ADD_COOKIE, {"cookie": cookie_dict})File "E:\py脚本\comicup29-ticket-buy-main\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute self.error_handler.check_response(response) File "E:\py脚本\comicup29-ticket-buy-main\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response raise exception_class(message, screen, stacktrace) selenium.common.exceptions.InvalidCookieDomainException: Message: invalid cookie domain: Cookie 'domain' mismatch (Session info: chrome=111.0.5563.147) Stacktrace: Backtrace: (No symbol) [0x0086DCE3] (No symbol) [0x008039D1] ((No symbol) [0x00714DA8] (No symbol) [0x0077A8DF] (No symbol) [0x0075AECC] (No symbol) [0x0076D57C] (No symbol) [0x0075ACC6] (No symbol) [0x00736F68] (No symbol) [0x007380CD] GetHandleVerifier [0x00AE3832+2506274] GetHandleVerifier [0x00B19794+2727300] GetHandleVerifier [0x00B1E36C+2746716] GetHandleVerifier [0x00916690+617600] (No symbol) [0x0080C712] (No symbol) [0x00811FF8] (No symbol) [0x008120DB] (No symbol) [0x0081C63B] BaseThreadInitThunk [0x7646FA29+25] RtlGetAppContainerNamedObjectPath [0x779E7A7E+286] RtlGetAppContainerNamedObjectPath [0x779E7A4E+238]

你是自己手动填的config.json里的cookie吗，invalid cookie domain这个报错说你填了无关的域名

**Comment by gx2816** [comment]
非常感谢佬给我回复邮件，我重新运行脚本就可以了。
"qq_email_config": {
    "sender": "",
    "password": "",
    "receiver": ""
}
receiver这是我自己接收邮件的邮箱吗（我现在给大大发邮件的这个），sender这个邮箱请问是从哪获取的
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hobr/comicup29-ticket-buy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月23日(星期天) 中午12:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hobr/comicup29-ticket-buy] cookie无法解析 (Issue #1)





  
作者大大，请问为啥B站可以自动刷新，但是cpp运行后会打开页面报错后自动关闭 Traceback (most recent call last): File "E:/py脚本/comicup29-ticket-buy-main/cpp.py", line 34, in WebDriver.add_cookie( File "E:\py脚本\comicup29-ticket-buy-main\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 727, in add_cookie self.execute(Command.ADD_COOKIE, {"cookie": cookie_dict})File "E:\py脚本\comicup29-ticket-buy-main\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute self.error_handler.check_response(response) File "E:\py脚本\comicup29-ticket-buy-main\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response raise exception_class(message, screen, stacktrace) selenium.common.exceptions.InvalidCookieDomainException: Message: invalid cookie domain: Cookie 'domain' mismatch (Session info: chrome=111.0.5563.147) Stacktrace: Backtrace: (No symbol) [0x0086DCE3] (No symbol) [0x008039D1] ((No symbol) [0x00714DA8] (No symbol) [0x0077A8DF] (No symbol) [0x0075AECC] (No symbol) [0x0076D57C] (No symbol) [0x0075ACC6] (No symbol) [0x00736F68] (No symbol) [0x007380CD] GetHandleVerifier [0x00AE3832+2506274] GetHandleVerifier [0x00B19794+2727300] GetHandleVerifier [0x00B1E36C+2746716] GetHandleVerifier [0x00916690+617600] (No symbol) [0x0080C712] (No symbol) [0x00811FF8] (No symbol) [0x008120DB] (No symbol) [0x0081C63B] BaseThreadInitThunk [0x7646FA29+25] RtlGetAppContainerNamedObjectPath [0x779E7A7E+286] RtlGetAppContainerNamedObjectPath [0x779E7A4E+238]
  
你是自己手动填的config.json里的cookie吗，invalid cookie domain这个报错说你填了无关的域名

**Comment by Hobr** [comment]
> 非常感谢佬给我回复邮件，我重新运行脚本就可以了。 "qq_email_config": { "sender": "", "password": "", "receiver": "" } receiver这是我自己接收邮件的邮箱吗（我现在给大大发邮件的这个），sender这个邮箱请问是从哪获取的 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Hobr/comicup29-ticket-buy" ***@***.***&gt;; 发送时间:&nbsp;2023年4月23日(星期天) 中午12:47 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Hobr/comicup29-ticket-buy] cookie无法解析 (Issue #1) 作者大大，请问为啥B站可以自动刷新，但是cpp运行后会打开页面报错后自动关闭 Traceback (most recent call last): File "E:/py脚本/comicup29-ticket-buy-main/cpp.py", line 34, in WebDriver.add_cookie( File "E:\py脚本\comicup29-ticket-buy-main\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 727, in add_cookie self.execute(Command.ADD_COOKIE, {"cookie": cookie_dict})File "E:\py脚本\comicup29-ticket-buy-main\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute self.error_handler.check_response(response) File "E:\py脚本\comicup29-ticket-buy-main\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response raise exception_class(message, screen, stacktrace) selenium.common.exceptions.InvalidCookieDomainException: Message: invalid cookie domain: Cookie 'domain' mismatch (Session info: chrome=111.0.5563.147) Stacktrace: Backtrace: (No symbol) [0x0086DCE3] (No symbol) [0x008039D1] ((No symbol) [0x00714DA8] (No symbol) [0x0077A8DF] (No symbol) [0x0075AECC] (No symbol) [0x0076D57C] (No symbol) [0x0075ACC6] (No symbol) [0x00736F68] (No symbol) [0x007380CD] GetHandleVerifier [0x00AE3832+2506274] GetHandleVerifier [0x00B19794+2727300] GetHandleVerifier [0x00B1E36C+2746716] GetHandleVerifier [0x00916690+617600] (No symbol) [0x0080C712] (No symbol) [0x00811FF8] (No symbol) [0x008120DB] (No symbol) [0x0081C63B] BaseThreadInitThunk [0x7646FA29+25] RtlGetAppContainerNamedObjectPath [0x779E7A7E+286] RtlGetAppContainerNamedObjectPath [0x779E7A4E+238] 你是自己手动填的config.json里的cookie吗，invalid cookie domain这个报错说你填了无关的域名 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

sender就是发件邮箱 xxx@qq.com ~~至于能不能自己给自己发邮件我也没试过~~

**Comment by mdjso** [comment]
> 非常感谢佬给我回复邮件，我重新运行脚本就可以了。 "qq_email_config": { "sender": "", "password": "", "receiver": "" } receiver这是我自己接收邮件的邮箱吗（我现在给大大发邮件的这个），sender这个邮箱请问是从哪获取的 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Hobr/comicup29-ticket-buy" ***@***.***&gt;; 发送时间:&nbsp;2023年4月23日(星期天) 中午12:47 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Hobr/comicup29-ticket-buy] cookie无法解析 (Issue #1) 作者大大，请问为啥B站可以自动刷新，但是cpp运行后会打开页面报错后自动关闭 Traceback (most recent call last): File "E:/py脚本/comicup29-ticket-buy-main/cpp.py", line 34, in WebDriver.add_cookie( File "E:\py脚本\comicup29-ticket-buy-main\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 727, in add_cookie self.execute(Command.ADD_COOKIE, {"cookie": cookie_dict})File "E:\py脚本\comicup29-ticket-buy-main\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute self.error_handler.check_response(response) File "E:\py脚本\comicup29-ticket-buy-main\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response raise exception_class(message, screen, stacktrace) selenium.common.exceptions.InvalidCookieDomainException: Message: invalid cookie domain: Cookie 'domain' mismatch (Session info: chrome=111.0.5563.147) Stacktrace: Backtrace: (No symbol) [0x0086DCE3] (No symbol) [0x008039D1] ((No symbol) [0x00714DA8] (No symbol) [0x0077A8DF] (No symbol) [0x0075AECC] (No symbol) [0x0076D57C] (No symbol) [0x0075ACC6] (No symbol) [0x00736F68] (No symbol) [0x007380CD] GetHandleVerifier [0x00AE3832+2506274] GetHandleVerifier [0x00B19794+2727300] GetHandleVerifier [0x00B1E36C+2746716] GetHandleVerifier [0x00916690+617600] (No symbol) [0x0080C712] (No symbol) [0x00811FF8] (No symbol) [0x008120DB] (No symbol) [0x0081C63B] BaseThreadInitThunk [0x7646FA29+25] RtlGetAppContainerNamedObjectPath [0x779E7A7E+286] RtlGetAppContainerNamedObjectPath [0x779E7A4E+238] 你是自己手动填的config.json里的cookie吗，invalid cookie domain这个报错说你填了无关的域名 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

发件和收件邮箱可以是同一个
