### ISSUE TITLE
ticket这个获取的element不一定是5月2号的票

### ISSUE THREAD

**Issue by JasonLSS** [Hobr/comicup29-ticket-buy#13]
当有且仅有5月3号的选框可用时
`ticket = WebDriver.find_element(By.XPATH, "//*[@id='app']/div[2]/div[2]/div[2]/div[4]/ul[1]/li[2]/div[1]")`
由于b站机制，会把可用的放第一个div里，会找到5月3号的票
需要加个判断
`if '05-03' not in ticket.text:`
来避免这个问题

同理只买5月3号也需要最好加下约束。

**Comment by Hobr** [comment]
这个问题我这两天帮人在会员购捡漏时也发现了，但是这两天只能捡人家不要的，没的选，~~也就没管~~，有空了我加上相关的判断

**Comment by jamesgeziqian** [comment]
#14 应该是修好了？owner康康呗

**Comment by Hobr** [comment]
> #14 应该是修好了？owner康康呗

感谢~

**Comment by Hobr** [comment]
#14 已解决

**Comment by JasonLSS** [comment]
okok，看起来这样没问题
