### ISSUE TITLE
CPP.PY报错

### ISSUE THREAD

**Issue by lisafrank420** [Hobr/comicup29-ticket-buy#16]
File "C:\Users\k'k\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidCookieDomainException: Message: invalid cookie domain: Cookie 'domain' mismatch
  (Session info: chrome=103.0.5060.53)
Stacktrace:
Backtrace:
        Ordinal0 [0x00C06463+2188387]
        Ordinal0 [0x00B9E461+1762401]
        Ordinal0 [0x00AB3D78+802168]
        Ordinal0 [0x00B1B5F1+1226225]
        Ordinal0 [0x00AFC7DC+1099740]
        Ordinal0 [0x00B0CC22+1166370]
        Ordinal0 [0x00AFC5F6+1099254]
        Ordinal0 [0x00AD6BE0+945120]
        Ordinal0 [0x00AD7AD6+948950]
        GetHandleVerifier [0x00EA71F2+2712546]
        GetHandleVerifier [0x00E9886D+2652765]
        GetHandleVerifier [0x00C9002A+520730]
        GetHandleVerifier [0x00C8EE06+516086]
        Ordinal0 [0x00BA468B+1787531]
        Ordinal0 [0x00BA8E88+1805960]
        Ordinal0 [0x00BA8F75+1806197]
        Ordinal0 [0x00BB1DF1+1842673]
        BaseThreadInitThunk [0x76B40099+25]
        RtlGetAppContainerNamedObjectPath [0x776A7B6E+286]
        RtlGetAppContainerNamedObjectPath [0x776A7B3E+238]

使用chrome 103.0.5060.53 报错信息是这样 碍于我本人没有代码基础所以无法提供更多信息 抱歉

**Comment by lisafrank420** [comment]
已解决 解决方法是全程不要挂代理 获取cookies的时候忘了关梯子

**Comment by Hobr** [comment]
> 已解决 解决方法是全程不要挂代理 获取cookies的时候忘了关梯子

好多人都遇到了这个问题，可能不是代理的问题
