### ISSUE TITLE
第10步输完python .\bilibili.py后显示python: can't open file 'C:\\Users\\hello\\bilibili.py': [Errno 2] No such file or directory，求解！！

### ISSUE THREAD

**Issue by hackerinist** [Hobr/comicup29-ticket-buy#21]

**Comment by linya601** [comment]
我也是！卡在这步了。把directory换成正确路径后又出现：
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\comicup29-ticket-buy-main\comicup29-ticket-buy-main\bilibili.py", line 1, in <module>
    from selenium.webdriver.common.by import By
ModuleNotFoundError: No module named 'selenium'

**Comment by mdjso** [comment]
> hackerinist

意思是没有找到 .\bilibili.py 文件，需要终端的工作路径和这个文件在同一个路径才能这么运行。如果是windows的话可以用文件管理器打开项目文件夹，右键点“在终端打开”然后就可以这样运行

**Comment by hackerinist** [comment]
> > hackerinist
> 
> 意思是没有找到 .\bilibili.py 文件，需要终端的工作路径和这个文件在同一个路径才能这么运行。如果是windows的话可以用文件管理器打开项目文件夹，右键点“在终端打开”然后就可以这样运行

解决了，谢谢大佬

**Comment by hackerinist** [comment]
> @linya601 cmd使用命令“**pip install selenium**”重新安装selenium
解决了谢谢大佬

**Comment by linya601** [comment]
> 

哇解决了，谢谢大佬！

**Comment by linya601** [comment]
> @linya601 cmd使用命令“**pip install selenium**”重新安装selenium

哇解决了，谢谢大佬！
