### ISSUE TITLE
是否支持双人购票？

### ISSUE THREAD

**Issue by tsurumi-yizhou** [Hobr/comicup29-ticket-buy#5]
需要买两张票

**Comment by Hobr** [comment]
照猫画虎增加两行find_element().click()就行，第一个try里加一行点票数的加号，第二个try里加一行在下单页面选择另一个人信息，目前我这不会增加相关代码，不方便大多数人用
可以拿这个展子购买页面试试手 https://show.bilibili.com/platform/detail.html?id=72238&from=pc_order_detail

**Comment by tsurumi-yizhou** [comment]
谢谢啦
allcpp呢大佬，有模板吗

**Comment by Hobr** [comment]
> 谢谢啦 allcpp呢大佬，有模板吗

我刚刚去翻了半天，没找到其他要求身份证实名的活动，只能等第二轮售票时再研究了

**Comment by tsurumi-yizhou** [comment]
好吧qaq
